### ISSUE TITLE
##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'testOrClassName' because it is an empty string.

### ISSUE THREAD

**Issue by jeffchen-codingconsultantco** [ricardoserradas/RuntSQLtTests-AzDO#11]
I find out my tSQLt task failed because of following configuration:

I check the run all test checkbox.
![image](https://user-images.githubusercontent.com/12480770/55775981-8f9a3b80-5ade-11e9-8045-99dca4f74776.png)

when I debug the pipeline, I find following parameter settings:
##[debug]PowerShellHandler.Execute - AddParameter(queryTimeout=60)
##[debug]PowerShellHandler.Execute - AddParameter(runAllTests=true)
##[debug]PowerShellHandler.Execute - AddParameter(**testOrClassName=**)

However, I get following error when pipeline run tSQLt task:
##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'testOrClassName' because it is an empty string.

**Comment by jeffchen-codingconsultantco** [comment]
I fix the issue by saving the pipeline again.

**Comment by trisapeace** [comment]
I have the same issue in my pipelines when I have the "Run all test suites and test cases" checkbox checked.

Saving the pipeline again didn't work for me. I even tried deleting the "Run tSQlt Unit Tests" plugin and adding it again with all the same parameters and that also had the same issue.

My guess is because it's marked as a required parameter. Could someone please re-open this issue?
